    export const RecipeCard = [
    {id:"1",
    totalcalories:"150",
    name:"Licuado",
    clasification:["Alta en proteinas", "Baja en carbohidratos", "Moderada en grasas"],
    preparation:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    link:"/",
    ingredients:["Frijol", "Plátano"],
    protein:"8",
    carbohydrates:"192",
    fats:"9"
    },
    {id:"2",
    totalcalories:"150",
    name:"Pizza",
    clasification:["Alta en proteinas", "Baja en carbohidratos", "Moderada en grasas"],
    preparation:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    link:"/",
    ingredients:["Pollo", "Plátano"],
    protein:"8",
    carbohydrates:"192",
    fats:"9"
    },
    {id:"3",
    totalcalories:"150",
    name:"Lonche",
    clasification:["Alta en proteinas", "Baja en carbohidratos", "Moderada en grasas"],
    preparation:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    link:"/",
    ingredients:["Manzana", "Plátano"],
    protein:"8",
    carbohydrates:"192",
    fats:"9"
    },
    {id:"4",
    totalcalories:"150",
    name:"Pollo a la plancha",
    clasification:["Alta en proteinas", "Baja en carbohidratos", "Moderada en grasas"],
    preparation:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    link:"/",
    ingredients:["Manzana", "Plátano"],
    protein:"8",
    carbohydrates:"192",
    fats:"9"
    },
    {id:"5",
    totalcalories:"150",
    name:"Spaghetti a la bolognesa",
    clasification:["Alta en proteinas", "Baja en carbohidratos", "Moderada en grasas"],
    preparation:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    link:"/",
    ingredients:["Manzana", "Plátano"],
    protein:"8",
    carbohydrates:"192",
    fats:"9"
    },
]