export const ExerciseCard = [
    {
        id:'1',
        name:"Curl",
        totalcalories:"269",	
        muscles:["Bicep"],	
        difficulty: "Baja",
        indications: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        preparation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        material: ["Mancuerna", "Barra"],
        type: "Pesas",
        injury: "",
    },
    {
        id:'2',
        name:"Sentadilla",
        muscles:["Cuadricep","Pantorilla", "Femoral"],	
        difficulty: "Alta",
        indications: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        preparation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        material: ["Barra"],
        type: "Pesas",
        injury: "",
    },
    {
        id:'3',
        name:"Pull up",
        muscles:["Bicep","Espalda"],	
        difficulty: "Baja",
        indications: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        preparation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        material: [],
        type: "Peso corporal",
        injury: "Hombro",
    },
    {
        id:'4',
        name:"Desplante",
        muscles:["Cuadricep"],	
        difficulty: "Alta",
        indications: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        preparation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        material: ["Mancuerna", "Barra"],
        type: "Pesas",
        injury: ""
    },
    {
        id:'5',
        name:"Trote",
        muscles:["Gluteo"],	
        difficulty: "Media",
        indications: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        preparation: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        material: [],
        type: "Cardiovascular",
        injury: ""
    },
]
