export const data =[
    {
        id: '1000',
        code: 'f230fh0g3',
        name: 'Suela',
        description: 'Product Description',
        image: 'bamboo-watch.jpg',
        price: 65,
        category: 'Accessories',
        quantity: 224,
        inventoryStatus: 'INSTOCK',
    },    {
        id: '1000',
        code: 'f230fh0g3',
        name: 'Suela',
        description: 'Product Description',
        image: 'bamboo-watch.jpg',
        price: 5,
        category: 'Accessories',
        quantity: 212341234,
        inventoryStatus: 'INSTOCK',
    },    {
        id: '1000',
        code: 'f230fh0g3',
        name: 'Suela',
        description: 'Product Description',
        image: 'bamboo-watch.jpg',
        price: 65,
        category: 'Accessories',
        quantity: 245,
        inventoryStatus: 'INSTOCK',
    },    {
        id: '1000',
        code: 'f230fh0g3',
        name: 'Suela',
        description: 'Product Description',
        image: 'bamboo-watch.jpg',
        price: 65,
        category: 'Accessories',
        quantity: 2434,
        inventoryStatus: 'INSTOCK',
    },    {
        id: '1000',
        code: 'f230fh0g3',
        name: 'Suela',
        description: 'Product Description',
        image: 'bamboo-watch.jpg',
        price: 65,
        category: 'Accessories',
        quantity: 2433,
        inventoryStatus: 'INSTOCK',
    },    {
        id: '1000',
        code: 'f230fh0g3',
        name: 'Suela',
        description: 'Product Description',
        image: 'bamboo-watch.jpg',
        price: 652,
        category: 'Accessories',
        quantity: 243,
        inventoryStatus: 'INSTOCK',
    },    {
        id: '1000',
        code: 'f230fh0g3',
        name: 'Suela',
        description: 'Product Description',
        image: 'bamboo-watch.jpg',
        price: 5,
        category: 'Accessories',
        quantity: 24,
        inventoryStatus: 'INSTOCK',
    },
]