export const APPOINTMENTS =[
    {
        id: 123,
        assignedBy: 1,
        assignedTo: 1203,
        place: 'https://maps.app.goo.gl/HXM61se4rSExvMep6',
        startsAt: new Date().getDate(),
        endsAt: new Date().getDate(),
        details: 'Descripción de la cita',
        status: 'Pendiente',
        date: new Date().getDate(),
    },
    {
        id: 1123423,
        assignedBy: 1,
        assignedTo: 1203,
        place: 'https://maps.app.goo.gl/HXM61se4rSExvMep6',
        startsAt: new Date().getDate(),
        endsAt: new Date().getDate(),
        details: 'Descripción de la cita',
        status: 'Completada',
        date: new Date().getDate(),
    },
    {
        id: 112323,
        assignedBy: 1,
        assignedTo: 1203,
        place: 'https://maps.app.goo.gl/HXM61se4rSExvMep6',
        startsAt: new Date().getDate(),
        endsAt: new Date().getDate(),
        details: 'Descripción de la cita',
        status: 'Cancelada',
        date: new Date().getDate(),
    },
    {
        id: 112456323,
        assignedBy: 1,
        assignedTo: 1203,
        place: 'https://maps.app.goo.gl/HXM61se4rSExvMep6',
        startsAt: new Date().getDate(),
        endsAt: new Date().getDate(),
        details: 'Descripción de la cita',
        status: 'Rechazada',
        date: new Date().getDate(),  
    },
    {
        id: 5,
        assignedBy: 1,
        assignedTo: 1252303,
        place: 'https://maps.app.goo.gl/HXM61se4rSExvMep6',
        startsAt: new Date().getDate(),
        endsAt: new Date().getDate(),
        details: 'Descripción de la cita',
        status: 'Aceptada',
        date: new Date().getDate(),  
    }
]